### ISSUE TITLE
Accessories appear as offline after restart

### ISSUE THREAD

**Issue by gdombiak** [beowulfe/HAP-Java#11]
Hi,

I started playing with this library and it is really impressive how well it works. I created my own HomekitAuthInfo that is persisting the mac, salt privateKey and also the userKeyMap. My problem is that after I restart the server, the iOS app shows all accessories as offline. I looked at socket connections to my server and after the restart, I do not see any new socket connection to port 9123.

What am I missing? Every time I have to reset HomeKit configuration and pair again. I tried debugging the code and I do not see any attempt from the iPhone to establish a new connection. I verified that all settings are correctly stored and retrieved. I see the process listening on port 9123 but nothing connected. :(

Any help is greatly appreciated.
Thanks,
Gaston

**Comment by beowulfe** [comment]
Are you implementing HomekitAuthInfo.hasUser? Starting with iOS8, the advertisement HomeKit makes includes a flag indicating whether the accessory is paired. If it advertises as unpaired (hasUser() returns false), iOS won't reconnect to it.

**Comment by gdombiak** [comment]
Andy,

YOU ARE THE BEST! Thanks so much for your quick reply. I implemented that method and it now works after the restart.

Amazing work you did on this library. :)

Thanks a lot. I'm now unblocked!
Gaston

**Comment by beowulfe** [comment]
Cool, glad it worked!
