### ISSUE TITLE
Stop advertising after pairing

### ISSUE THREAD

**Issue by andrelcm** [beowulfe/HAP-Java#22]
Why the server stop advertising after a device is paired? Isn't it possible to pair more devices to it?

**Comment by beowulfe** [comment]
Nope, it's a restriction of HomeKit that it can only be paired once. The pairing gets shared via iCloud to your other devices, and you can invite other users via iOS settings.

They started enforcing this in iOS 8 - if we didn't change the advertisement to indicate it was already paired, iOS refused to connect.

**Comment by andrelcm** [comment]
Ok, thank you for the quick response and for the great job.
