### ISSUE TITLE
Not working on Raspberry PI2 and OSGI Framework

### ISSUE THREAD

**Issue by marcoNieddu** [beowulfe/HAP-Java#23]
I Think that the problem is related on netty connections. It is not present any error on log.

**Comment by sumppen** [comment]
I managed to get it working on my RPi only after specifying the IP address to listen to (so it did not work with any address (0.0.0.0)

**Comment by marcoNieddu** [comment]
I tested it on OSGI. I have specified the InetAddress.  The problem is related to the netty connections, the Iphone is not receiving  the responses from the bridge.

**Comment by marcoNieddu** [comment]
I tested it on OSGI. I have specified the InetAddress.  The problem is related to the netty connections, the Iphone is not receiving  the responses from the bridge.
