### ISSUE TITLE
Question - publishing 

### ISSUE THREAD

**Issue by Phreak87** [beowulfe/HAP-Java#35]
Hello,

How can I push a changed value to the client?
Let's say we have a switch and I change the internal 
Value from true to false. How does the client update its own status ? Is it always a get -> response or can I push the new value directly via a open channel via notify client. How do I do this if this is possible ?

**Comment by beowulfe** [comment]
Many of the characteristics support a subscription mechanism. A client that's interested in receiving pushed updates sends a subscription request. You then call the callback passed to the subscribe* method when the value changes.
