### ISSUE TITLE
Problem with openhabian distibution of your library

### ISSUE THREAD

**Issue by trailblazer2006** [beowulfe/HAP-Java#37]
I have installed openhenhab 2.1 on Raspberry with HomeKit addon. I have read your solution to the problem with a thermostat here https://github.com/beowulfe/HAP-Java/commit/9ba46a5b0363a1f954b039e678b1b911cac74650, but I do not understand how to update the file on my Raspberry . Help me please.

**Comment by trailblazer2006** [comment]
Hi consult with developer of openhabian release and he told me that the distribution is not using the latest version of your library. https://github.com/openhab/openhabian/issues/175. His recommendation is to update the version, but I do not really understand where to do it. As I understand it, nap-java is installed with HoteKit addon for openhab. I have the version 2.1.0 installed. Tell me what to do?

**Comment by trailblazer2006** [comment]
Я понял свои дальнейшие шаги. Очень признателен за вашу помощь.

**Comment by ThomDietrich** [comment]
I think you misunderstood something. 

@beowulfe when were you planning to release a nev version of the HAP-Java?

**Comment by beowulfe** [comment]
Yeah, I suppose I should at least update with the newest version of this dependency. I was hoping to just package it up with the new accessory types, but the blocker there is... taking longer than expected :)

I'll try to push an update this weekend.

**Comment by trailblazer2006** [comment]
Hi guys, When do you plan to release a new version?

**Comment by neohusky** [comment]
@beowulfe and @ThomDietrich 
Sorry to bump this thread. I'm having similar no response using using a thermostat group. 

Has there been an update to this issue?

**Comment by frank-f** [comment]
I'm using openHAB 2.4.0 and the issue still exists. Anyone ever going to look at this?

**Comment by frank-f** [comment]
Since the actual bug in this library has been fixed ages ago I took the liberty and created a pull request to deploy the update to openHAB, which is the real problem here. This issue report should be closed since there's nothing that can be done here.

openhab/openhab2-addons#4535
