### ISSUE TITLE
Can not connect to device

### ISSUE THREAD

**Issue by hpposch** [beowulfe/HAP-Java#42]
Hi,
I really like this project and I already got the example working.
But at the moment I can not connect to the server.
I see the following message in the log:

`17:15:35,424 INFO  [com.beowulfe.hap.impl.pairing.PairingManager] (defaultEventExecutorGroup-4-1) Starting pair for loxone Miniserver
17:15:35,512 INFO  [com.beowulfe.hap.impl.http.HomekitClientConnection] (defaultEventExecutorGroup-4-1) 200 /pair-setup
17:15:35,683 INFO  [com.beowulfe.hap.impl.http.HomekitClientConnection] (defaultEventExecutorGroup-4-1) 200 /pair-setup
17:15:35,705 INFO  [stdout] (defaultEventExecutorGroup-4-1) Added pairing for 5a:d2:5c:df:cd:1e1F86E0D6-ADAF-4BDD-9B1B-1C9617D4F79A
17:15:35,705 INFO  [com.beowulfe.hap.impl.jmdns.JmdnsHomekitAdvertiser] (defaultEventExecutorGroup-4-1) Re-creating service due to change in discoverability to false
17:15:37,712 INFO  [com.beowulfe.hap.impl.jmdns.JmdnsHomekitAdvertiser] (defaultEventExecutorGroup-4-1) Registering _hap._tcp.local. on port 9123
17:15:40,469 INFO  [com.beowulfe.hap.impl.http.HomekitClientConnection] (defaultEventExecutorGroup-4-1) 200 /pair-setup
17:15:40,469 INFO  [com.beowulfe.hap.impl.http.impl.AccessoryHandler] (defaultEventExecutorGroup-4-1) Terminated homekit connection from /192.168.3.39:53734`

Here the app gets "stuck" and after a while it tells me that de device could not be added.

Does anyone know why this happens?

Thanks in advance for your help :)

**Comment by beowulfe** [comment]
That usually happens when the response from the server fails validation in iOS. If you check the iOS console logs, it should give you more details.

**Comment by hpposch** [comment]
Ok thanks, i will check that :)

**Comment by hpposch** [comment]
I don't really see anything in the device logs.
But the strange thing is when I execute my code as a standalone application it works.
I already posted it here: https://github.com/beowulfe/HAP-Java/issues/27
So I guess it is a problem with multithreading.

**Comment by hpposch** [comment]
I did a little bit of testing now and I will share my results with you:

When I start the application standalone as a java application I see the following LOG entries:

`
The PIN for pairing is 031-45-154
Restored username f2:30:6d:3f:2:b61F86E0D6-ADAF-4BDD-9B1B-1C9617D4F79A key [B@2ff4f00f
Username f2:30:6d:3f:2:b61F86E0D6-ADAF-4BDD-9B1B-1C9617D4F79A restored.
Private key =  uS��Ky�Nq7�{w��h�ě��6.��uV��
Mac = f2:30:6d:3f:2:b6
Salt = 21035573755269516438474454234649011193
Bridge started.
Jän 12, 2018 2:41:51 PM io.netty.handler.logging.LoggingHandler channelRegistered
INFORMATION: [id: 0xc9600a04] REGISTERED
Jän 12, 2018 2:41:51 PM io.netty.handler.logging.LoggingHandler bind
INFORMATION: [id: 0xc9600a04] BIND(0.0.0.0/0.0.0.0:9123)
Has users? yes.
Jän 12, 2018 2:41:55 PM io.netty.handler.logging.LoggingHandler channelActive
INFORMATION: [id: 0xc9600a04, /0:0:0:0:0:0:0:0:9123] ACTIVE
`
Everything works fine, I can connect to my bridge and all switches work as expected.


When I start the same application inside my application server (Wildly 8) the LOG Output is completely different:

`
14:43:54,111 INFO  [stdout] (ServerService Thread Pool -- 50) The PIN for pairing is 031-45-154
14:43:54,119 INFO  [stdout] (ServerService Thread Pool -- 50) Restored username f2:30:6d:3f:2:b61F86E0D6-ADAF-4BDD-9B1B-1C9617D4F79A key [B@3c396990
14:43:54,119 INFO  [stdout] (ServerService Thread Pool -- 50) Username f2:30:6d:3f:2:b61F86E0D6-ADAF-4BDD-9B1B-1C9617D4F79A restored.
14:43:54,119 INFO  [stdout] (ServerService Thread Pool -- 50) Private key =  uS��Ky�Nq7�{w��h�ě��6.��uV��
14:43:54,119 INFO  [stdout] (ServerService Thread Pool -- 50) Mac = f2:30:6d:3f:2:b6
14:43:54,119 INFO  [stdout] (ServerService Thread Pool -- 50) Salt = 21035573755269516438474454234649011193
14:43:54,146 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory loxone Miniserver
14:43:57,149 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Büro Arbeiten
14:43:57,149 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Büro Entspannen
14:43:57,149 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Büro Bewegen
14:43:57,149 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Büro Nachtmodus
14:43:57,149 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Büro Farblicht1
14:43:57,149 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Büro Farblicht2
14:43:57,149 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Büro Farblicht3
14:43:57,149 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Büro Farblicht4
14:43:57,149 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Büro Alles
14:43:57,149 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Büro nächste Szene
14:43:57,149 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Büro vorherige Szene
14:43:57,149 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Vorraum Alles
14:43:57,149 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Vorraum nächste Szene
14:43:57,149 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Vorraum vorherige Szene
14:43:57,149 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Außenbereich Alles
14:43:57,149 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Außenbereich nächste Szene
14:43:57,149 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Außenbereich vorherige Szene
14:43:57,149 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Dachboden xx_Lesen
14:43:57,149 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Dachboden xx_Schlafen
14:43:57,149 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Dachboden xx_Chillen
14:43:57,149 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Dachboden xx_Nachtlicht
14:43:57,149 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Dachboden xx_Bewegen
14:43:57,149 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Dachboden Alles
14:43:57,149 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Dachboden nächste Szene
14:43:57,149 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Dachboden vorherige Szene
14:43:57,150 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Zentral Bewegung
14:43:57,150 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Zentral Alles
14:43:57,150 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Zentral nächste Szene
14:43:57,150 INFO  [com.beowulfe.hap.HomekitRoot] (ServerService Thread Pool -- 50) Added accessory Zentral vorherige Szene
14:43:57,243 INFO  [io.netty.handler.logging.LoggingHandler] (nioEventLoopGroup-2-1) [id: 0x21ea5765] REGISTERED
14:43:57,245 INFO  [stdout] (ServerService Thread Pool -- 50) Bridge started.
14:43:57,245 INFO  [io.netty.handler.logging.LoggingHandler] (nioEventLoopGroup-2-1) [id: 0x21ea5765] BIND(0.0.0.0/0.0.0.0:9123)
14:43:57,246 INFO  [com.beowulfe.hap.impl.http.impl.NettyHomekitHttpService] (nioEventLoopGroup-2-1) Bound homekit listener to /0.0.0.0:9123
14:43:57,247 INFO  [stdout] (nioEventLoopGroup-2-1) Has users? yes.
14:43:57,247 INFO  [com.beowulfe.hap.impl.jmdns.JmdnsHomekitAdvertiser] (nioEventLoopGroup-2-1) Advertising accessory loxone Miniserver
14:43:57,247 INFO  [com.beowulfe.hap.impl.jmdns.JmdnsHomekitAdvertiser] (nioEventLoopGroup-2-1) Registering _hap._tcp.local. on port 9123
14:44:01,701 INFO  [io.netty.handler.logging.LoggingHandler] (nioEventLoopGroup-2-1) [id: 0x21ea5765, /0.0.0.0:9123] ACTIVE
`

The first thing I noticed here is that the process of adding the accessories is later than in the standalone application.
Further I saw these two Log entries:

`
Jän 12, 2018 2:41:51 PM io.netty.handler.logging.LoggingHandler channelRegistered
....
Jän 12, 2018 2:41:55 PM io.netty.handler.logging.LoggingHandler channelActive
`

I guess I might has something to do with these two Log entries ---> the code behind of course...
Since there is no active channel on the bridge it is clear that my App can not connect to it!

I hope this information can help you, if you ned an example to reproduce this I can create a new project for you where you can test this.
But normally it is enough when you start your example within a new Thread.

**Comment by nathanjskelton** [comment]
How are you de Loving your app? Wildfly is a JEE app server ... It will try to manage the threads for you and may have unpredictable results if you don’t use managed thread pools. Try launching in a thread from a standard java app or a war running in tomcat... it will probably work as expected. If you need to stick with a JEE architecture look into managed thread pools.

**Comment by nathanjskelton** [comment]
“Deploying” not “de loving” ...  typing on an iPhone while taking care of a sick two-year-old is challenging work

**Comment by hpposch** [comment]
OK i will check that, maybe this is the thing.
Thanks for your answer.

Btw, All the best for your child :)
