### ISSUE TITLE
Restarting looses pairings

### ISSUE THREAD

**Issue by comdata** [beowulfe/HAP-Java#7]
Hi,

I've taken the sample application and added a reloading of the keys, salt and mac and also the user map.

Nonetheless the elements are shown as not connected in the EVE app.

Any ideas?

Kind Regards

**Comment by beowulfe** [comment]
Try turning on trace level logging - you may get an idea from there. If not, paste the logs in here (it will reveal your key, so if you're concerned about security, you might want to wipe the stored one afterwards)

**Comment by comdata** [comment]
Hi,

so far I had no luck enabling trace logging. Any hints what an how to do it?

**Comment by beowulfe** [comment]
In the sample app, you can change it in logback.xml: https://github.com/beowulfe/HAP-Java/blob/sample/src/main/resources/logback.xml#L24

Replace DEBUG with TRACE

**Comment by comdata** [comment]
Hi,

I found the issue. It was a problem with saving the private/public keys.

Thanks for the support.
