### ISSUE TITLE
Persisting fails

### ISSUE THREAD

**Issue by comdata** [beowulfe/HAP-Java#8]
Hi again,

I tried persisting the settings but so far I had no luck getting this to work.

The following is my AuthInfo class.

As far as I can see there is no request coming from my phone when the service comes back alive.

Any ideas?

---------------------------------------------
package cm.homeautomation.hap;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.InvalidAlgorithmParameterException;
import java.util.Properties;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;

import org.apache.commons.codec.binary.Base64;

import com.beowulfe.hap.HomekitAuthInfo;
import com.beowulfe.hap.HomekitServer;

/**
 */
public class AuthInfoService implements HomekitAuthInfo {

	private static String PIN = "032-45-154";

	private static String mac;
	private static BigInteger salt;
	private static byte[] privateKey;
	private static ConcurrentMap<String, byte[]> userKeyMap = new ConcurrentHashMap<>();

	public AuthInfoService() throws InvalidAlgorithmParameterException {

		Properties props = new Properties();
		try {
			InputStream resourceAsStream = new FileInputStream(new File("/home/hap/" + "server.properties"));

			if (resourceAsStream != null) {
				props.load(resourceAsStream);
			}
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		if (props.getProperty("mac") != null) {
			System.out.println("using existing config");
			mac = props.getProperty("mac");
			salt = new BigInteger(Base64.decodeBase64((String) props.get("salt")));

			privateKey = readKey("privateKey");

			System.out.println(new String(privateKey));
			System.out.println(mac);
			System.out.println(salt);

			loadUsers();

		} else {
			System.out.println("generating new config");
			mac = "04:a1:51:69:94:55";// HomekitServer.generateMac();
			salt = HomekitServer.generateSalt();
			privateKey = HomekitServer.generateKey();
			System.out.println("SALT: " + salt);
			System.out.println("KEY: " + new String(privateKey));
			saveParamChanges(mac, salt, privateKey);

			saveKey("privateKey", privateKey);
		}

		System.out.println(
				"Auth info is generated each time the sample application is started. Pairings are not persisted.");
		System.out.println("The PIN for pairing is " + PIN);
	}

	public byte[] readKey(String string) {
		try {
			File f = new File("/home/hap/" + string);
			FileInputStream fis = new FileInputStream(f);
			DataInputStream dis = new DataInputStream(fis);
			byte[] keyBytes = new byte[(int) f.length()];
			dis.readFully(keyBytes);
			dis.close();

			return keyBytes;
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return null;
	}

	public void saveKey(String name, byte[] privateKey2) {
		// TODO Auto-generated method stub
		DataOutputStream keyfos;
		try {
			keyfos = new DataOutputStream(new FileOutputStream("/home/hap/" + name, false));

			keyfos.write(privateKey2);
			keyfos.close();
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	public void loadUsers() {

		try {
			InputStream resourceAsStream = new FileInputStream(new File("/home/hap/" + "usermap.xml"));
			Properties props = new Properties();

			if (resourceAsStream != null) {
				System.out.println("Loading user map");
				props.loadFromXML(resourceAsStream);

				Set<Object> keySet = props.keySet();

				for (Object keyObject : keySet) {

					String key = (String) keyObject;

					byte[] publicKey = readKey(key);
					if (publicKey != null) {
						System.out.println("Loading " + key + " " + new String(publicKey));
						userKeyMap.putIfAbsent(key, publicKey);
					}
				}
			} else {
				System.out.println("File empty");
			}
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	public void saveParamChanges(String mac, BigInteger salt, byte[] privateKey) {
		try {
			Properties props = new Properties();
			props.setProperty("mac", mac);
			props.setProperty("salt", "" + new String(Base64.encodeBase64(salt.toByteArray())));

			File f = new File("/home/hap/" + "server.properties");
			OutputStream out = new FileOutputStream(f);
			props.store(out, "This is an optional header comment string");
			System.out.println("SALT: " + new BigInteger(Base64.decodeBase64((String) props.get("salt"))));
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public void saveUserMap() {
		try {
			Properties props = new Properties();

			Set<String> keySet = userKeyMap.keySet();
			for (String key : keySet) {
				props.setProperty(key, key);

				saveKey(key, userKeyMap.get(key));
			}

			File f = new File("/home/hap/" + "usermap.xml");
			OutputStream out = new FileOutputStream(f);
			props.storeToXML(out, "This is an optional header comment string");
		} catch (Exception e) {
			e.printStackTrace();
		}

	}

	@Override
	public String getPin() {
		return PIN;
	}

	@Override
	public String getMac() {
		return mac;
	}

	@Override
	public BigInteger getSalt() {
		return salt;
	}

	@Override
	public byte[] getPrivateKey() {
		return privateKey;
	}

	@Override
	public void createUser(String username, byte[] publicKey) {

		if (userKeyMap.containsKey(username)) {
			System.out.println("Performing key update");
			userKeyMap.replace(username, publicKey);
		} else {
			System.out.println("Adding initial key");
			userKeyMap.putIfAbsent(username, publicKey);
		}

		saveUserMap();
		System.out.println("Added pairing for " + username + " " + new String(publicKey));
	}

	@Override
	public void removeUser(String username) {
		userKeyMap.remove(username);
		saveUserMap();
		System.out.println("Removed pairing for " + username);
	}

	@Override
	public byte[] getUserPublicKey(String username) {
		System.out.println();
		byte[] bs = userKeyMap.get(username);
		System.out.println("Requesting User:" + username + " " + new String(bs));

		return bs;
	}

}

**Comment by mickwheelz** [comment]
I am having similar issues with persistance. I have attempted several ways to store the data on disk but each files. attached is my auth code



[HomeKitAuth.txt](https://github.com/beowulfe/HAP-Java/files/79854/HomeKitAuth.txt)

**Comment by mickwheelz** [comment]
I have since resolved the issue (and am also storing the persisted data using java.util.prefs)

If you are running iOS 9 or later, you need to override the hasUser() function in your auth implementation

e.g

@Override
	public boolean hasUser() {
		return prefs.getBoolean(hasUser, false);
	}

**Comment by comdata** [comment]
Hi Mick,

do you mind sharing more of your Authentication Code?

Thanks

**Comment by beowulfe** [comment]
The openhab2 add-on is probably too complicated to be a true reference implementation, but you might get some good ideas from how its using the library: https://github.com/openhab/openhab2-addons/blob/master/addons/io/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAuthInfoImpl.java

**Comment by comdata** [comment]
Thanks.

I changed a bit and this is working.

package cm.homeautomation.hap;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.math.BigInteger;
import java.security.InvalidAlgorithmParameterException;
import java.util.Base64;
import java.util.Collection;
import java.util.HashSet;
import java.util.Properties;
import java.util.Set;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.beowulfe.hap.HomekitAuthInfo;
import com.beowulfe.hap.HomekitServer;

/**
 * Provides a mechanism to store authenticated homekit client details inside the
 * ESH StorageService, by implementing HomekitAuthInfo.
 *
 * @author Andy Lintner
 */
public class HomekitAuthInfoImpl implements HomekitAuthInfo {

	class StorageService {
		public Storage getStorage() {
			return new Storage("/home/hap/homekit.xml");
		}
	}

	class Storage {
		private String file;
		private Properties props;

		public Storage(String file) {
			this.file = file;
			try {
				props = new Properties();
				InputStream resourceAsStream = new FileInputStream(new File(file));
				

				if (resourceAsStream != null) {
					System.out.println("Loading properties");
					props.loadFromXML(resourceAsStream);

				} else {
					System.out.println("File empty");
				}
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

		public void put(String key, String value) {
			props.put(key, value);
			store(props);
		}

		private void store(Properties properties) {
			try {
				File f = new File(file);
				OutputStream out = new FileOutputStream(f);
				properties.storeToXML(out, "This is an optional header comment string");
			} catch (Exception e) {
				e.printStackTrace();
			}

		}

		public String get(String key) {
			if (props != null) {
				return (String) props.get(key);
			}
			return null;
		}

		public Collection<String> getKeys() {
			HashSet<String> keys = new HashSet<String>();

			Set<Object> keySet = props.keySet();

			for (Object keyObject : keySet) {

				String key = (String) keyObject;
				keys.add(key);
			}

			return keys;
		}

		public void remove(String key) {
			props.remove(key);
			store(props);
		}
	}

	private final Storage storage;
	private final String mac;
	private final BigInteger salt;
	private final byte[] privateKey;
	private final String pin;
	private Logger logger = LoggerFactory.getLogger(HomekitAuthInfoImpl.class);

	public HomekitAuthInfoImpl(String pin) throws InvalidAlgorithmParameterException {
		storage = new StorageService().getStorage();
		initializeStorage();
		this.pin = pin;
		mac = storage.get("mac");
		salt = new BigInteger(storage.get("salt"));
		privateKey = Base64.getDecoder().decode(storage.get("privateKey"));
	}

	@Override
	public void createUser(String username, byte[] publicKey) {
		storage.put(createUserKey(username), Base64.getEncoder().encodeToString(publicKey));
	}

	@Override
	public String getMac() {
		return mac;
	}

	@Override
	public String getPin() {
		return pin;
	}

	@Override
	public byte[] getPrivateKey() {
		return privateKey;
	}

	@Override
	public BigInteger getSalt() {
		return salt;
	}

	@Override
	public byte[] getUserPublicKey(String username) {
		String encodedKey = storage.get(createUserKey(username));
		if (encodedKey != null) {
			return Base64.getDecoder().decode(encodedKey);
		} else {
			return null;
		}
	}

	@Override
	public void removeUser(String username) {
		storage.remove(createUserKey(username));
	}

	@Override
	public boolean hasUser() {
		Collection<String> keys = storage.getKeys();
		return keys.stream().filter(k -> isUserKey(k)).count() > 0;
	}

	public void clear() {
		for (String key : new HashSet<>(storage.getKeys())) {
			if (isUserKey("user_")) {
				storage.remove(key);
			}
		}
	}

	private String createUserKey(String username) {
		return "user_" + username;
	}

	private boolean isUserKey(String key) {
		return key.startsWith("user_");
	}

	private void initializeStorage() throws InvalidAlgorithmParameterException {
		if (storage.get("mac") == null) {
			logger.warn("Could not find existing MAC in " + storage.getClass().getName()
					+ ". Generating new MAC. This will require re-pairing of iOS devices.");
			storage.put("mac", HomekitServer.generateMac());
		}
		if (storage.get("salt") == null) {
			storage.put("salt", HomekitServer.generateSalt().toString());
		}
		if (storage.get("privateKey") == null) {
			storage.put("privateKey", Base64.getEncoder().encodeToString(HomekitServer.generateKey()));
		}
	}

}
