### ISSUE TITLE
library not working on Debian Jessie (ARM, x64)

### ISSUE THREAD

**Issue by mickwheelz** [beowulfe/HAP-Java#9]
I have been unable to connect to the HomeKit bridge when then application is running (my code, and basic example code)

I can telnet to the IP on the correct port and the app registered a connection, but cannot connect using HomeKit Catalog, or EVE

However, the example code (and my own code) works fine on Mac OS X and Windows 7.

I thought at first it might be something to do with the ARM arcitecture of the Pi, however after trying it on Debian Jessie x64 (on the same machine I tested under windows 7 on) I am thinking it has something to do with debian jessie

**Comment by rain3k** [comment]
hm.. me too..
i want to work in raspberry pi 2.so i try to run  in raspberry pi 2.
but .. this library didn't work......
i think ....network,port is fine....  
this library work in my mac book pc...but don't work in raspberry pi.......

**Comment by beowulfe** [comment]
If you're not already, try using the InetAddress argument in the HomekitServer constructor. Java's decision when determining that progmatically seems off on some platforms.

**Comment by mickwheelz** [comment]
I've tried adding that argument to the HomekitServer constructor, does not seem to make a difference.

e.g

InetAddress in = InetAddress.getLocalHost();
HomekitServer homekit = new HomekitServer(in, PORT);

**Comment by beowulfe** [comment]
That's the same thing the constructor without the argument does. Try passing in an InetAddress for the IP bound to the interface you want the service on - Java is likely picking a different one (i.e. a local unused interface)

**Comment by mickwheelz** [comment]
I've tested the below on both Raspbian Jessie (RPi Zero) and Debian Jessie (x64) and can confirm its working fine.

e.g 

InetAddress in = InetAddress.getByName("192.168.0.31");
HomekitServer homekit = new HomekitServer(in, PORT);

thanks @beowulfe for the suggestions and thanks again for providing this library :)

**Comment by beowulfe** [comment]
Great! Glad it worked!

**Comment by rglorius** [comment]
Hi there,

i've got the library working glad on my Mac and i can still connect via Home-App. Thats very nice!

But on my Raspi3 there is still an error. After the usage of the InetAddress hint from mickwheelz the bridge still appears in the Home-App, but after insert the Security-Token the connection fails. 

Do you have an tip for ip settings on the raspi or an other solution? 

Best regards, 
Robert
